on:
  push:
    branches:
      - main
    paths:
      - "service/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Service
        id: get_service
        run: echo ::set-output name=SERVICE::$(echo ${{ matrix.workspaces.name }} | cut -d / -f 2)

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.REGISTRY_URL }}

      - name: Docker Build
        run: yarn docker build @service/${{steps.get_service.outputs.SERVICE}} -t ${{ secrets.REGISTRY_URL }}/${{steps.get_service.outputs.SERVICE}}

      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY_URL }}
