on:
  push:
    branches:
      - main
    paths:
      - "service/admin/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.REGISTRY_URL }}

      - name: Docker Build
        run: yarn docker build @service/admin -t ${{ secrets.REGISTRY_URL }}/admin

      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY_URL }}/admin
