on:
  push:
    branches:
      - main
    paths:
      - "service/main/**"
      - "packages/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.REGISTRY_URL }}

      - name: Docker Build
        run: yarn docker build @service/main -t ${{ secrets.REGISTRY_URL }}/main

      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY_URL }}/main
